### PR TITLE
BR-4441 - Fix test that are failing

### PR DESCRIPTION
**Pull request by dhiraj-toptal**

### CODE REVIEW

**Review by raimonbal — COMMENTED** [review]
can you put a screenshot of the tests passing?

**Comment by dhiraj-toptal** [comment]
ViewModel-test
Plugin-test
observer-test
helper-test
controller_test

**Comment by dhiraj-toptal** [comment]
ViewModel, Plugin, Controller, Observer, Helper directory Tests are completed. 
There are still some issues to be sorted in Block and Model directories. 
@omergilad  @raimonbal

**Comment by omergilad** [comment]
@dhiraj-toptal so this one doesn't include all test fixes?

**Review by omergilad — APPROVED** [review]

**Pull request merged**
